"""Hardcoded seed data for the cost-comparison demo.

All pricing here is SYNTHETIC. The hospital names and locations are real, but
every dollar figure is generated by app.pricing and bears no relationship to
what these institutions actually charge.
"""

from dataclasses import dataclass

from .models import Hospital, Procedure


@dataclass(frozen=True)
class HospitalSeed:
    id: str
    name: str
    address: str
    city: str
    state: str
    zip_code: str
    lat: float
    lng: float
    phone: str
    # Synthetic pricing knobs: academic medical centers run high, community
    # hospitals low, and self-pay discounts vary independently of list price.
    price_multiplier: float
    self_pay_discount_rate: float

    def to_model(self) -> Hospital:
        return Hospital(
            id=self.id,
            name=self.name,
            address=self.address,
            city=self.city,
            state=self.state,
            zip_code=self.zip_code,
            lat=self.lat,
            lng=self.lng,
            phone=self.phone,
        )


@dataclass(frozen=True)
class ProcedureSeed:
    code: str
    name: str
    description: str
    base_price: int
    # Share of total fees billed by the physician rather than the facility.
    # Lab draws are almost entirely facility; surgery is not.
    physician_share: float
    # None means "we don't know" — reserved for codes not in this catalog.
    medicare_covered: bool | None = True

    def to_model(self) -> Procedure:
        return Procedure(
            code=self.code,
            name=self.name,
            description=self.description,
            medicare_covered=self.medicare_covered,
        )


HOSPITALS: list[HospitalSeed] = [
    HospitalSeed(
        id="mgh",
        name="Massachusetts General Hospital",
        address="55 Fruit St",
        city="Boston",
        state="MA",
        zip_code="02114",
        lat=42.3631,
        lng=-71.0687,
        phone="(617) 726-2000",
        price_multiplier=1.42,
        self_pay_discount_rate=0.58,
    ),
    HospitalSeed(
        id="bwh",
        name="Brigham and Women's Hospital",
        address="75 Francis St",
        city="Boston",
        state="MA",
        zip_code="02115",
        lat=42.3360,
        lng=-71.1065,
        phone="(617) 732-5500",
        price_multiplier=1.38,
        self_pay_discount_rate=0.55,
    ),
    HospitalSeed(
        id="bidmc",
        name="Beth Israel Deaconess Medical Center",
        address="330 Brookline Ave",
        city="Boston",
        state="MA",
        zip_code="02215",
        lat=42.3389,
        lng=-71.1058,
        phone="(617) 667-7000",
        price_multiplier=1.30,
        self_pay_discount_rate=0.52,
    ),
    HospitalSeed(
        id="dfci",
        name="Dana-Farber Cancer Institute",
        address="450 Brookline Ave",
        city="Boston",
        state="MA",
        zip_code="02215",
        lat=42.3376,
        lng=-71.1074,
        phone="(617) 632-3000",
        price_multiplier=1.35,
        self_pay_discount_rate=0.50,
    ),
    HospitalSeed(
        id="tufts",
        name="Tufts Medical Center",
        address="800 Washington St",
        city="Boston",
        state="MA",
        zip_code="02111",
        lat=42.3495,
        lng=-71.0634,
        phone="(617) 636-5000",
        price_multiplier=1.24,
        self_pay_discount_rate=0.47,
    ),
    HospitalSeed(
        id="bmc",
        name="Boston Medical Center",
        address="1 Boston Medical Center Pl",
        city="Boston",
        state="MA",
        zip_code="02118",
        lat=42.3345,
        lng=-71.0723,
        phone="(617) 638-8000",
        price_multiplier=1.18,
        self_pay_discount_rate=0.62,
    ),
    HospitalSeed(
        id="faulkner",
        name="Brigham and Women's Faulkner Hospital",
        address="1153 Centre St",
        city="Jamaica Plain",
        state="MA",
        zip_code="02130",
        lat=42.3016,
        lng=-71.1288,
        phone="(617) 983-7000",
        price_multiplier=1.02,
        self_pay_discount_rate=0.44,
    ),
    HospitalSeed(
        id="ste",
        name="St. Elizabeth's Medical Center",
        address="736 Cambridge St",
        city="Brighton",
        state="MA",
        zip_code="02135",
        lat=42.3524,
        lng=-71.1447,
        phone="(617) 789-3000",
        price_multiplier=0.98,
        self_pay_discount_rate=0.41,
    ),
    HospitalSeed(
        id="mtauburn",
        name="Mount Auburn Hospital",
        address="330 Mount Auburn St",
        city="Cambridge",
        state="MA",
        zip_code="02138",
        lat=42.3742,
        lng=-71.1300,
        phone="(617) 492-3500",
        price_multiplier=1.05,
        self_pay_discount_rate=0.46,
    ),
    HospitalSeed(
        id="cha",
        name="Cambridge Health Alliance - Cambridge Hospital",
        address="1493 Cambridge St",
        city="Cambridge",
        state="MA",
        zip_code="02139",
        lat=42.3736,
        lng=-71.1006,
        phone="(617) 665-1000",
        price_multiplier=0.88,
        self_pay_discount_rate=0.64,
    ),
    HospitalSeed(
        id="nwh",
        name="Newton-Wellesley Hospital",
        address="2014 Washington St",
        city="Newton",
        state="MA",
        zip_code="02462",
        lat=42.3268,
        lng=-71.2246,
        phone="(617) 243-6000",
        price_multiplier=1.08,
        self_pay_discount_rate=0.45,
    ),
    HospitalSeed(
        id="lahey",
        name="Lahey Hospital & Medical Center",
        address="41 Mall Rd",
        city="Burlington",
        state="MA",
        zip_code="01805",
        lat=42.4906,
        lng=-71.2130,
        phone="(781) 744-5100",
        price_multiplier=1.12,
        self_pay_discount_rate=0.48,
    ),
    HospitalSeed(
        id="winchester",
        name="Winchester Hospital",
        address="41 Highland Ave",
        city="Winchester",
        state="MA",
        zip_code="01890",
        lat=42.4520,
        lng=-71.1370,
        phone="(781) 729-9000",
        price_multiplier=0.95,
        self_pay_discount_rate=0.43,
    ),
    HospitalSeed(
        id="melrosewakefield",
        name="MelroseWakefield Hospital",
        address="585 Lebanon St",
        city="Melrose",
        state="MA",
        zip_code="02176",
        lat=42.4520,
        lng=-71.0620,
        phone="(781) 979-3000",
        price_multiplier=0.86,
        self_pay_discount_rate=0.51,
    ),
    HospitalSeed(
        id="salem",
        name="Salem Hospital",
        address="81 Highland Ave",
        city="Salem",
        state="MA",
        zip_code="01970",
        lat=42.5150,
        lng=-70.9070,
        phone="(978) 741-1200",
        price_multiplier=0.92,
        self_pay_discount_rate=0.49,
    ),
    HospitalSeed(
        id="beverly",
        name="Beverly Hospital",
        address="85 Herrick St",
        city="Beverly",
        state="MA",
        zip_code="01915",
        lat=42.5680,
        lng=-70.8790,
        phone="(978) 922-3000",
        price_multiplier=0.90,
        self_pay_discount_rate=0.47,
    ),
    HospitalSeed(
        id="emerson",
        name="Emerson Hospital",
        address="133 Old Road to Nine Acre Corner",
        city="Concord",
        state="MA",
        zip_code="01742",
        lat=42.4490,
        lng=-71.3720,
        phone="(978) 369-1400",
        price_multiplier=0.94,
        self_pay_discount_rate=0.42,
    ),
    HospitalSeed(
        id="southshore",
        name="South Shore Hospital",
        address="55 Fogg Rd",
        city="South Weymouth",
        state="MA",
        zip_code="02190",
        lat=42.1770,
        lng=-70.9440,
        phone="(781) 624-8000",
        price_multiplier=0.97,
        self_pay_discount_rate=0.45,
    ),
]


PROCEDURES: list[ProcedureSeed] = [
    ProcedureSeed(
        code="36415,80048",
        name="Blood test, basic group of blood chemicals (Calcium, total)",
        description=(
            "Basic metabolic panel including total calcium, carbon dioxide, "
            "chloride, creatinine, glucose, potassium, sodium, urea nitrogen; "
            "collected by venipuncture"
        ),
        base_price=870,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="71046",
        name="Chest X-ray, 2 views",
        description="Radiologic examination of the chest, frontal and lateral views",
        base_price=320,
        physician_share=0.14,
    ),
    ProcedureSeed(
        code="97110",
        name="Physical therapy, therapeutic exercise",
        description=(
            "Therapeutic procedure, one or more areas, each 15 minutes; "
            "therapeutic exercises to develop strength, endurance, and flexibility"
        ),
        base_price=175,
        physician_share=0.05,
    ),
    ProcedureSeed(
        code="93306",
        name="Echocardiogram, complete with Doppler",
        description=(
            "Transthoracic echocardiography for congenital cardiac anomalies; "
            "complete, with spectral and color flow Doppler"
        ),
        base_price=1450,
        physician_share=0.16,
    ),
    ProcedureSeed(
        code="74177",
        name="CT scan, abdomen and pelvis with contrast",
        description=(
            "Computed tomography of the abdomen and pelvis with contrast material, "
            "including image post-processing"
        ),
        base_price=2100,
        physician_share=0.12,
    ),
    ProcedureSeed(
        code="70551",
        name="MRI brain without contrast",
        description=(
            "Magnetic resonance imaging of the brain, including brain stem, "
            "without contrast material"
        ),
        base_price=2400,
        physician_share=0.12,
    ),
    ProcedureSeed(
        code="45378",
        name="Colonoscopy, diagnostic",
        description=(
            "Colonoscopy, flexible; diagnostic, including collection of specimen "
            "by brushing or washing, when performed"
        ),
        base_price=2800,
        physician_share=0.22,
    ),
    ProcedureSeed(
        code="43239",
        name="Upper GI endoscopy with biopsy",
        description=(
            "Esophagogastroduodenoscopy, flexible, transoral; with biopsy, "
            "single or multiple"
        ),
        base_price=3100,
        physician_share=0.22,
    ),
    ProcedureSeed(
        code="66984",
        name="Cataract surgery with lens implant",
        description=(
            "Extracapsular cataract removal with insertion of intraocular lens "
            "prosthesis, one stage"
        ),
        base_price=4200,
        physician_share=0.24,
    ),
    ProcedureSeed(
        code="29881",
        name="Knee arthroscopy with meniscectomy",
        description=(
            "Arthroscopy, knee, surgical; with meniscectomy including any "
            "meniscal shaving"
        ),
        base_price=9800,
        physician_share=0.20,
    ),
    ProcedureSeed(
        code="59400",
        name="Vaginal delivery, routine obstetric care",
        description=(
            "Routine obstetric care including antepartum care, vaginal delivery, "
            "and postpartum care"
        ),
        base_price=12500,
        physician_share=0.26,
    ),
    ProcedureSeed(
        code="27447",
        name="Total knee replacement",
        description=(
            "Arthroplasty, knee, condyle and plateau; medial and lateral "
            "compartments with or without patella resurfacing"
        ),
        base_price=38000,
        physician_share=0.18,
    ),
    # --- Labs ---
    ProcedureSeed(
        code="80061",
        name="Lipid panel",
        description=(
            "Blood test measuring total cholesterol, HDL, LDL, and triglycerides"
        ),
        base_price=210,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="83036",
        name="Hemoglobin A1c",
        description="Blood test measuring average blood glucose over ~3 months",
        base_price=145,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="80048",
        name="Basic metabolic panel",
        description=(
            "Blood test measuring calcium, carbon dioxide, chloride, creatinine, "
            "glucose, potassium, sodium, and urea nitrogen"
        ),
        base_price=185,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="80053",
        name="Comprehensive metabolic panel",
        description=(
            "Blood test measuring 14 substances including liver and kidney markers"
        ),
        base_price=245,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="85025",
        name="Complete blood count with differential",
        description="Blood test measuring red cells, white cells, and platelets",
        base_price=160,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="84443",
        name="Thyroid stimulating hormone (TSH)",
        description="Blood test assessing thyroid function",
        base_price=175,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="81001",
        name="Urinalysis with microscopy",
        description="Automated urinalysis with microscopic examination",
        base_price=95,
        physician_share=0.03,
    ),
    ProcedureSeed(
        code="82043",
        name="Urine albumin, microalbumin",
        description="Quantitative urine albumin test to screen for kidney damage",
        base_price=120,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="82306",
        name="Vitamin D level",
        description="Blood test measuring 25-hydroxyvitamin D",
        base_price=225,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="87070",
        name="Bacterial culture",
        description="Culture of specimen for identification of bacterial organisms",
        base_price=190,
        physician_share=0.03,
    ),
    ProcedureSeed(
        code="36415",
        name="Blood draw (venipuncture)",
        description="Collection of a venous blood specimen by venipuncture",
        base_price=45,
        physician_share=0.0,
    ),
    # --- Imaging ---
    ProcedureSeed(
        code="77067",
        name="Screening mammogram, both breasts",
        description=(
            "Screening mammography, bilateral, including computer-aided detection"
        ),
        base_price=480,
        physician_share=0.14,
    ),
    ProcedureSeed(
        code="77080",
        name="Bone density scan (DEXA)",
        description=(
            "Dual-energy X-ray absorptiometry of the hip and spine to assess "
            "bone mineral density"
        ),
        base_price=330,
        physician_share=0.13,
    ),
    ProcedureSeed(
        code="76805",
        name="Obstetric ultrasound, after first trimester",
        description=(
            "Ultrasound of the pregnant uterus, fetal and maternal evaluation, "
            "after the first trimester"
        ),
        base_price=620,
        physician_share=0.16,
    ),
    ProcedureSeed(
        code="76801",
        name="Obstetric ultrasound, first trimester",
        description=(
            "Ultrasound of the pregnant uterus, fetal and maternal evaluation, "
            "first trimester"
        ),
        base_price=580,
        physician_share=0.16,
    ),
    ProcedureSeed(
        code="73721",
        name="MRI joint of lower extremity without contrast",
        description=(
            "Magnetic resonance imaging of any joint of the lower extremity, "
            "without contrast material"
        ),
        base_price=2250,
        physician_share=0.12,
    ),
    ProcedureSeed(
        code="73030",
        name="X-ray of shoulder",
        description="Radiologic examination of the shoulder, minimum two views",
        base_price=290,
        physician_share=0.14,
    ),
    ProcedureSeed(
        code="76700",
        name="Abdominal ultrasound, complete",
        description="Ultrasound of the abdomen, real time with image documentation",
        base_price=650,
        physician_share=0.15,
    ),
    # --- Office visits and preventive care ---
    ProcedureSeed(
        code="99213",
        name="Office visit, established patient, low complexity",
        description=(
            "Office or outpatient visit for an established patient, "
            "20-29 minutes of total time"
        ),
        base_price=185,
        physician_share=0.62,
    ),
    ProcedureSeed(
        code="99214",
        name="Office visit, established patient, moderate complexity",
        description=(
            "Office or outpatient visit for an established patient, "
            "30-39 minutes of total time"
        ),
        base_price=265,
        physician_share=0.62,
    ),
    ProcedureSeed(
        code="99396",
        name="Preventive visit, established patient, age 40-64",
        description=(
            "Periodic comprehensive preventive medicine reevaluation, "
            "established patient, 40-64 years"
        ),
        base_price=340,
        physician_share=0.60,
        medicare_covered=False,  # Medicare covers G0439 instead
    ),
    ProcedureSeed(
        code="G0439",
        name="Annual wellness visit, subsequent",
        description=(
            "Annual wellness visit including a personalized prevention plan, "
            "subsequent visit"
        ),
        base_price=290,
        physician_share=0.60,
    ),
    ProcedureSeed(
        code="99483",
        name="Cognitive assessment and care planning",
        description=(
            "Assessment of and care planning for a patient with cognitive "
            "impairment, typically 60 minutes"
        ),
        base_price=520,
        physician_share=0.58,
    ),
    ProcedureSeed(
        code="96127",
        name="Brief emotional or behavioral assessment",
        description=(
            "Brief emotional/behavioral assessment with scoring and documentation, "
            "e.g. depression or anxiety screening"
        ),
        base_price=60,
        physician_share=0.30,
    ),
    ProcedureSeed(
        code="99406",
        name="Smoking cessation counseling, intermediate",
        description="Smoking and tobacco use cessation counseling, 3-10 minutes",
        base_price=55,
        physician_share=0.65,
    ),
    # --- Therapy ---
    ProcedureSeed(
        code="97116",
        name="Physical therapy, gait training",
        description="Therapeutic procedure, gait training, each 15 minutes",
        base_price=170,
        physician_share=0.05,
    ),
    ProcedureSeed(
        code="97530",
        name="Physical therapy, therapeutic activities",
        description=(
            "Therapeutic activities to improve functional performance, "
            "direct patient contact, each 15 minutes"
        ),
        base_price=180,
        physician_share=0.05,
    ),
    ProcedureSeed(
        code="90834",
        name="Psychotherapy, 45 minutes",
        description="Individual psychotherapy with the patient, 45 minutes",
        base_price=210,
        physician_share=0.70,
    ),
    ProcedureSeed(
        code="97802",
        name="Medical nutrition therapy, initial assessment",
        description=(
            "Medical nutrition therapy, initial assessment and intervention, "
            "each 15 minutes"
        ),
        base_price=110,
        physician_share=0.40,
    ),
    # --- Cardiac ---
    ProcedureSeed(
        code="93000",
        name="Electrocardiogram (EKG), complete",
        description=(
            "Routine electrocardiogram with at least 12 leads, "
            "including interpretation and report"
        ),
        base_price=175,
        physician_share=0.20,
    ),
    ProcedureSeed(
        code="93017",
        name="Cardiac stress test, tracing only",
        description=(
            "Cardiovascular stress test using maximal or submaximal treadmill "
            "or bicycle exercise; tracing only"
        ),
        base_price=760,
        physician_share=0.18,
    ),
    # --- Vaccines ---
    ProcedureSeed(
        code="90686",
        name="Influenza vaccine",
        description=(
            "Quadrivalent influenza virus vaccine, preservative free, "
            "for intramuscular use"
        ),
        base_price=70,
        physician_share=0.05,
    ),
    ProcedureSeed(
        code="90732",
        name="Pneumococcal vaccine",
        description=(
            "Pneumococcal polysaccharide vaccine, 23-valent, for adult use"
        ),
        base_price=155,
        physician_share=0.05,
    ),
    ProcedureSeed(
        code="90715",
        name="Tdap vaccine",
        description=(
            "Tetanus, diphtheria toxoids and acellular pertussis vaccine, "
            "for adult use"
        ),
        base_price=95,
        physician_share=0.05,
    ),
    # --- Dental (commonly excluded from Medicare) ---
    ProcedureSeed(
        code="D1110",
        name="Dental cleaning (prophylaxis), adult",
        description="Removal of plaque, calculus, and stains from the teeth",
        base_price=145,
        physician_share=0.0,
        medicare_covered=False,
    ),
    ProcedureSeed(
        code="D4341",
        name="Periodontal scaling and root planing, per quadrant",
        description=(
            "Deep cleaning below the gum line for periodontal disease, "
            "four or more teeth per quadrant"
        ),
        base_price=390,
        physician_share=0.0,
        medicare_covered=False,
    ),
    # --- Added after sampling what the extractor actually returns on this
    # --- dataset: obstetric care, nurse visits, and the wider lab panel.
    ProcedureSeed(
        code="99211",
        name="Nurse visit, established patient",
        description=(
            "Office or outpatient visit that may not require the presence of a "
            "physician; typically 5 minutes"
        ),
        base_price=75,
        physician_share=0.25,
    ),
    ProcedureSeed(
        code="99212",
        name="Office visit, established patient, straightforward",
        description=(
            "Office or outpatient visit for an established patient, "
            "10-19 minutes of total time"
        ),
        base_price=130,
        physician_share=0.62,
    ),
    ProcedureSeed(
        code="99215",
        name="Office visit, established patient, high complexity",
        description=(
            "Office or outpatient visit for an established patient, "
            "40-54 minutes of total time"
        ),
        base_price=365,
        physician_share=0.62,
    ),
    ProcedureSeed(
        code="59425",
        name="Antepartum care, 4-6 visits",
        description="Antepartum care only; 4-6 prenatal visits",
        base_price=1450,
        physician_share=0.70,
    ),
    ProcedureSeed(
        code="59426",
        name="Antepartum care, 7 or more visits",
        description="Antepartum care only; 7 or more prenatal visits",
        base_price=2650,
        physician_share=0.70,
    ),
    ProcedureSeed(
        code="80051",
        name="Electrolyte panel",
        description=(
            "Blood test measuring carbon dioxide, chloride, potassium, and sodium"
        ),
        base_price=140,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="83540",
        name="Iron level",
        description="Blood test measuring serum iron",
        base_price=110,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="84484",
        name="Troponin, quantitative",
        description="Blood test measuring troponin to assess for cardiac injury",
        base_price=230,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="85610",
        name="Prothrombin time (PT)",
        description="Blood clotting test, often used to monitor warfarin therapy",
        base_price=90,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="87086",
        name="Urine culture, quantitative colony count",
        description="Quantitative bacterial culture of urine with colony count",
        base_price=155,
        physician_share=0.03,
    ),
    ProcedureSeed(
        code="87491",
        name="Chlamydia testing, amplified probe",
        description="Chlamydia trachomatis detection by nucleic acid amplification",
        base_price=175,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="88175",
        name="Cervical cytology (Pap smear)",
        description=(
            "Cervical or vaginal cytology screening by automated system with "
            "manual rescreening under physician supervision"
        ),
        base_price=185,
        physician_share=0.12,
    ),
    ProcedureSeed(
        code="86580",
        name="Tuberculosis skin test",
        description="Tuberculosis intradermal skin test (PPD / Tine)",
        base_price=85,
        physician_share=0.05,
    ),
    ProcedureSeed(
        code="82947",
        name="Blood glucose, quantitative",
        description="Quantitative blood glucose test, non-reagent strip",
        base_price=65,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="81025",
        name="Urine pregnancy test",
        description="Urine pregnancy test by visual color comparison",
        base_price=55,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="93010",
        name="Electrocardiogram, interpretation and report",
        description="Routine electrocardiogram; interpretation and report only",
        base_price=95,
        physician_share=0.85,
    ),
    ProcedureSeed(
        code="D0120",
        name="Periodic oral evaluation, established patient",
        description="Routine dental examination for an established patient",
        base_price=120,
        physician_share=0.0,
        medicare_covered=False,
    ),
    ProcedureSeed(
        code="99395",
        name="Preventive visit, established patient, age 18-39",
        description=(
            "Periodic comprehensive preventive medicine reevaluation, "
            "established patient, 18-39 years"
        ),
        base_price=300,
        physician_share=0.60,
        medicare_covered=False,  # Medicare covers G0439 instead
    ),
    ProcedureSeed(
        code="90656",
        name="Influenza vaccine, preservative free",
        description=(
            "Trivalent influenza virus vaccine, preservative free, "
            "for intramuscular use"
        ),
        base_price=68,
        physician_share=0.05,
    ),
    ProcedureSeed(
        code="86003",
        name="Allergen specific IgE testing",
        description="Allergen specific IgE blood test, quantitative, each allergen",
        base_price=80,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="86008",
        name="Allergen specific IgE, multiallergen screen",
        description="Allergen specific IgE, qualitative multiallergen screen",
        base_price=115,
        physician_share=0.02,
    ),
    ProcedureSeed(
        code="87110",
        name="Chlamydia culture",
        description="Culture of chlamydia from any source",
        base_price=165,
        physician_share=0.03,
    ),
    ProcedureSeed(
        code="87850",
        name="Gonorrhea testing, amplified probe",
        description="Neisseria gonorrhoeae detection by nucleic acid amplification",
        base_price=170,
        physician_share=0.02,
    ),
]


# Stand-in for a geocoding service: zip -> approximate centroid.
ZIP_CENTROIDS: dict[str, tuple[float, float]] = {
    "01742": (42.4600, -71.3490),  # Concord
    "01801": (42.4870, -71.1520),  # Woburn
    "01803": (42.4790, -71.2000),  # Burlington
    "01805": (42.5000, -71.2100),  # Burlington (Lahey)
    "01890": (42.4520, -71.1470),  # Winchester
    "01915": (42.5580, -70.8800),  # Beverly
    "01970": (42.5190, -70.8960),  # Salem
    "02108": (42.3576, -71.0655),  # Beacon Hill
    "02109": (42.3660, -71.0540),  # North End
    "02110": (42.3560, -71.0520),  # Financial District
    "02111": (42.3510, -71.0630),  # Chinatown
    "02113": (42.3660, -71.0550),
    "02114": (42.3617, -71.0680),  # West End
    "02115": (42.3430, -71.0950),  # Longwood
    "02116": (42.3500, -71.0760),  # Back Bay
    "02118": (42.3370, -71.0720),  # South End
    "02119": (42.3240, -71.0840),  # Roxbury
    "02120": (42.3320, -71.0950),  # Mission Hill
    "02121": (42.3080, -71.0850),
    "02122": (42.2930, -71.0550),
    "02124": (42.2870, -71.0710),  # Dorchester
    "02125": (42.3160, -71.0570),
    "02126": (42.2750, -71.0930),  # Mattapan
    "02127": (42.3340, -71.0400),  # South Boston
    "02128": (42.3780, -71.0250),  # East Boston
    "02129": (42.3780, -71.0620),  # Charlestown
    "02130": (42.3090, -71.1150),  # Jamaica Plain
    "02131": (42.2870, -71.1230),  # Roslindale
    "02132": (42.2800, -71.1610),  # West Roxbury
    "02134": (42.3550, -71.1310),  # Allston
    "02135": (42.3480, -71.1550),  # Brighton
    "02136": (42.2550, -71.1290),  # Hyde Park
    "02138": (42.3790, -71.1290),  # Cambridge
    "02139": (42.3650, -71.1040),  # Cambridge
    "02140": (42.3920, -71.1290),  # Cambridge
    "02141": (42.3700, -71.0850),  # Cambridge
    "02142": (42.3630, -71.0830),  # Kendall
    "02143": (42.3810, -71.0990),  # Somerville
    "02144": (42.4000, -71.1220),  # Somerville
    "02145": (42.3900, -71.0900),  # Somerville
    "02148": (42.4290, -71.0450),  # Malden
    "02149": (42.4080, -71.0540),  # Everett
    "02150": (42.3950, -71.0350),  # Chelsea
    "02151": (42.4180, -71.0000),  # Revere
    "02155": (42.4230, -71.1050),  # Medford
    "02169": (42.2510, -71.0030),  # Quincy
    "02176": (42.4560, -71.0640),  # Melrose
    "02180": (42.4780, -71.1000),  # Stoneham
    "02184": (42.2100, -70.9970),  # Braintree
    "02190": (42.1740, -70.9430),  # South Weymouth
    "02210": (42.3480, -71.0400),  # Seaport
    "02215": (42.3470, -71.1030),  # Fenway
    "02446": (42.3430, -71.1210),  # Brookline
    "02458": (42.3520, -71.1870),  # Newton
    "02460": (42.3450, -71.2080),  # Newtonville
    "02462": (42.3260, -71.2450),  # Newton Lower Falls
    "02472": (42.3700, -71.1770),  # Watertown
    "02474": (42.4160, -71.1560),  # Arlington
    "02476": (42.4180, -71.1830),  # Arlington
    "02478": (42.3960, -71.1780),  # Belmont
}


def find_procedure(code: str) -> ProcedureSeed | None:
    """Look up by exact code, or by the first code of a composite entry."""
    normalized = code.strip().replace(" ", "")
    for procedure in PROCEDURES:
        if procedure.code == normalized:
            return procedure
        if normalized in procedure.code.split(","):
            return procedure
    return None
